### ISSUE TITLE
Use parameters set in Customize mode to be applied in Schedule mode

### ISSUE THREAD

**Issue by Nwardezir** [VictorioBerra/trianglify-desktop-wallpaper#1]
Everything is in the title 😄 

I think plenty users will mainly generate the type of wallpaper they like with proper dimensions and options and would be delighted to keep these options on every new wallpaper generated through schedule.

**Comment by VictorioBerra** [comment]
A new version is releasing now, and its got a custom color picker! Let me know if this bug has been fixed for you and if you find any other issues.

**Comment by Nwardezir** [comment]
It's fixed indeed with last version.
As I use two 4K monitors, landscape oriented, I want to use is a wallpaper with the size being 7680 width by 2160 height, everything is 👍 now, thanks !

**Comment by Nwardezir** [comment]
Just noticed that every time you restart the app, dimension values aren't saved and default (2195x1235) is restored, might be tedious to use 😞

**Comment by VictorioBerra** [comment]
A new version is deploying now. It should save your width and height settings and I added a "reset" button to pull the orig settings.

**Comment by VictorioBerra** [comment]
Also, just curious, where are you installing the app from? Here in the GitHub release? Are you on Window or Linux?

**Comment by Nwardezir** [comment]
I'm on Win10 (clean and up-to-date) and installing from https://github.com/VictorioBerra/trianglify-desktop-wallpaper/releases

**Comment by VictorioBerra** [comment]
Are we good to close this issue?
