### ISSUE TITLE
3 bugs found in Trianglify (Linux Appimage)

### ISSUE THREAD

**Issue by LinuxBeaver** [VictorioBerra/trianglify-desktop-wallpaper#3]
Hello, I am interested in using this software for graphical task and I think it has a lot of potential if it worked properly.  In this post I will highlight three major shortcomings within the app.  Before I begin I want to point out I have a two monitor setup (standard notebook(1600x900) and a vertical screen1366x768). 

![image](https://user-images.githubusercontent.com/78667207/109869448-c3495600-7c60-11eb-810c-28035724d67d.png)

**1.** The applications screen size does not fit either of my monitors and the scroll feature appears to not function. I have to use "alt+drag" techniques to access custom palettes. 

 Below I will list my 1600x900 and 1366x768 to show how these programs fair on my screen.

1600x900 default
![image](https://user-images.githubusercontent.com/78667207/109870944-94cc7a80-7c62-11eb-9926-7e90b71136d9.png)

![image](https://user-images.githubusercontent.com/78667207/109869749-2affa100-7c61-11eb-8d93-7b592e656443.png)

1366x768 Vertical Setup
![image](https://user-images.githubusercontent.com/78667207/109869825-45397f00-7c61-11eb-8025-029e6e962710.png)

**2** I cannot change the directory of where the wallpaper is saved. I go to edit>Preferences and change the default folder to /home/USERNAME/Pictures/Trianglify_Workstation/ and save, but every time I restart the app the default folder is recreated.

**RETRACTED*** **--this is an issue having to do with a bug on the Cinnamon Desktop on Linux--**
**3** Closing the app does not really close it, nor does it create a taskbar indication that it is still open. The GNOME task manager is telling me that it is continuing to run in the background, and the only known work around is to xkill the process or with the task manager.

Other then that this app seems very useful and I appreciate its simplicity.  I even have an idea of an option to export to Gimp and Krita. Thank you for reading this request.  I hope we can troubleshoot these problems. Linux has very few graphical applications and this tool has the potential of being useful for triangle background generation.

**Comment by VictorioBerra** [comment]
Thanks! I will look into these. I struggled a lot with getting the app to be responsive to both large and smaller monitors. I have a 4k monitor so maybe I can simulate both your monitor sizes to get this working.

The app should minimize to tray and only close by right clicking the Tray icon and clicking quit. OR click "File" -> "Quit" and it will quit instantly.

It just uses the Electron Tray plugin. This issue makes it look like there might be some issues with it on GNOME https://github.com/electron/electron/issues/21445 if you find a solution there, please let me know.

I will look into save folder location as well and report back. Might take me a few days to get to all this.

**Comment by LinuxBeaver** [comment]
> Thanks! I will look into these. I struggled a lot with getting the app to be responsive to both large and smaller monitors. I have a 4k monitor so maybe I can simulate both your monitor sizes to get this working.
> 
> The app should minimize to tray and only close by right clicking the Tray icon and clicking quit. OR click "File" -> "Quit" and it will quit instantly.
> 
> It just uses the Electron Tray plugin. This issue makes it look like there might be some issues with it on GNOME [electron/electron#21445](https://github.com/electron/electron/issues/21445) if you find a solution there, please let me know.
> 
> I will look into save folder location as well and report back. Might take me a few days to get to all this.

I am using the Cinnamon Desktop, which is a fork of early GNOME 3. It has went its separate way since and is still on X window system. 

Thank you.

**Comment by VictorioBerra** [comment]
2.1.1 fixes the save path issue.

**Comment by LinuxBeaver** [comment]
> 2.1.1 fixes the save path issue.

Thanks

I would like to retract the third bug about the program failing to exit. I have noticed it displays a taskbar icon. The Cinnamon Desktop (v 4.2) on Linux appears to have a glitch where I have to refresh the Desktop to get it to display. This is a problem on my side.

**Comment by VictorioBerra** [comment]
Down to one last bug then! So, it looks like all we have to do is make scrolling work and that should at least get you going, right?

**Comment by LinuxBeaver** [comment]
> Down to one last bug then! So, it looks like all we have to do is make scrolling work and that should at least get you going, right?

Yes, but it would be easier if the app adjusted to my 1600x900 better. Because even if it did scroll I would not be able to even see the first custom palette template.

**Comment by VictorioBerra** [comment]
Yeah maybe I will make it keep everything on the right side (2-column layout) and then shrink the preview VS dropping into a 1-column layout.

To be fair, 1600x900 is a crazy resolution ;) but I agree it should at least be usable.

**Comment by VictorioBerra** [comment]
Released v2.2.0 please give it a try. It should allow you to scroll inside the app to get to things that might be hidden now. I also took the time to bump a few of the dependencies. A quick manual test found nothing major but, you never know.

**Comment by LinuxBeaver** [comment]
Thank you it appears to be working perfect!

However, I found another issue.

-One pixel off error--
If i make wallpaper 1200x900 pixels or any size. It makes it one pixel smaller 1999x899 ect.. this happens on everything and I just found out about it. Gimp and Nomacs report the same one pixel off error.

**Comment by VictorioBerra** [comment]
That is very odd, on windows I do not see the issue:

![image](https://user-images.githubusercontent.com/2934507/110949507-4c6b2780-8308-11eb-9ba8-4bcee93229a2.png)

Can you tell me whats in your config file located at: `$XDG_CONFIG_HOME` or `~/.config` and the name of the folder will be trianglify or something like that and the file should be config.json. Can you paste the contents here?

**Comment by LinuxBeaver** [comment]
![image](https://user-images.githubusercontent.com/78667207/110965076-c670d000-834b-11eb-854b-0e25bff6b6a3.png)

I searched for config and could not find anything.

However I found 'vuex.json' and it has this

`{
	"state": {
		"settings": {
			"image": {
				"savePath": "/home/USERNAME/Pictures/Trianglify_Workstation",
				"saveFolder": null
			}
		},
		"enableRandomCron": false,
		"randomCronWebhook": null,
		"randomCronExpression": "0 0 1 */1 *",
		"triangleVariance": 0.6,
		"patternIntensity": 0.93,
		"cellSize": 0.19,
		"fill": true,
		"strokeWidth": "0",
		"selectedColorPallet": "YlOrRd",
		"selectedCustomColorPalette": "0d7729da-34e4-4f6c-94f4-f9fd6a1978dc",
		"customColorPalettes": {
			"01e56cda-d556-4eb2-ae3c-fc53cfe73149": [
				"#BA68C8",
				"#C62828",
				"#FF4400",
				"#EE8C8B"
			],
			"09480e93-18c1-4a2c-b4da-c8c8b225b565": [
				"#3800FF",
				"#E8F8FF",
				"#7100FF",
				"#FFD7E4",
				"#0057FF",
				"#ABA3D3"
			],
			"2b8aeb88-35fd-4dc5-942d-7f08b6020b26": [
				"#03A9F4",
				"#3949AB",
				"#7E57C2",
				"#00BCD4",
				"#7E57C2",
				"#03A9F4",
				"#2E0DA1",
				"#03D3EE"
			],
			"adca2acf-1a23-492a-8e32-cd1b99aea86b": [
				"#1bc894",
				"#00b7aa",
				"#7B1FA2",
				"#008fbf",
				"#0079b9",
				"#2061a6"
			],
			"0d7729da-34e4-4f6c-94f4-f9fd6a1978dc": [
				"#59066F",
				"#6218BD",
				"#9281BF",
				"#6504FF",
				"#5D32A8",
				"#3949AB"
			],
			"132821e4-479d-418a-8801-31b00b3ccb83": [
				"#D81B60",
				"#FFFFFF",
				"#9443FF",
				"#FF3D00",
				"#005EFF",
				"#7B1FA2"
			],
			"5775f4dd-9d9d-4b6a-943f-c0f1ee6451a3": [
				"#9ebcda",
				"#8c96c6",
				"#8c6bb1",
				"#88419d"
			],
			"0499ea0f-751c-4244-938a-aeaaca683127": [
				"#e0b262",
				"#c8a552",
				"#b19743",
				"#9a8a34",
				"#837d27",
				"#6d7019"
			],
			"01822f3b-751b-427c-abb5-d42b06ccdcba": [
				"#5e2779",
				"#832a6f",
				"#9c3665",
				"#ad495c",
				"#b76057",
				"#bc7758"
			],
			"21d78d99-9537-40e0-953c-6e31f26463e6": [
				"#36748b",
				"#44919b",
				"#61ada5",
				"#8ac8ab",
				"#bae2b2",
				"#f0f9bd"
			]
		},
		"paletteTab": 1,
		"selectedScreenHeight": "901",
		"selectedScreenWidth": "1601"
	}
}`

**Comment by LinuxBeaver** [comment]
Here is the file incase this is hard to read

https://cdn.discordapp.com/attachments/631886211547529217/819963584535593010/vuex.json

**Comment by VictorioBerra** [comment]
Thats the right file, I see you have it set to `"selectedScreenHeight": "901", "selectedScreenWidth": "1601"` looks like you were seeing if you bump it by 1, if that would fix it. Just curious, did that fix it?

That file is like the apps database. Its got all your settings and custom pallets and your schedule and all that.

**Comment by LinuxBeaver** [comment]
> Thats the right file, I see you have it set to `"selectedScreenHeight": "901", "selectedScreenWidth": "1601"` looks like you were seeing if you bump it by 1, if that would fix it. Just curious, did that fix it?
> 
> That file is like the apps database. Its got all your settings and custom pallets and your schedule and all that.

That is due to me manually setting +1 pixel to fix the bug I was reported.

![image](https://user-images.githubusercontent.com/78667207/111020882-d8408a80-83c0-11eb-97a3-ac69409a21d1.png)

**Comment by VictorioBerra** [comment]
Right, I was wondering if that actually fixed it for you. I'm just curious.
