### ISSUE TITLE
Width x height convention

### ISSUE THREAD

**Issue by ls-1N** [VictorioBerra/trianglify-desktop-wallpaper#5]
Thanks for the lovely app.

I'm not an expert, but it seems like a common convention to have width before height when it comes to resolutions. I.e. 1920 x 1080, not 1080 x 1920. Currently in <kbd>Designer</kbd> > <kbd>Customize</kbd> it displays height first, then width.

If you'd like I can provide a list or even screenshot proof of examples where it is like that (and isn't).

Trianglify Wallpaper 2.2.0 on Kubuntu 18.04 via [snap](https://snapcraft.io/triangle-wallpaper).

**Comment by VictorioBerra** [comment]
Thanks! I can move those UI controls around without much effort.

**Comment by VictorioBerra** [comment]
Fixed by https://github.com/VictorioBerra/trianglify-desktop-wallpaper/pull/7
