### ISSUE TITLE
"About" button not working

### ISSUE THREAD

**Issue by ls-1N** [VictorioBerra/trianglify-desktop-wallpaper#6]
The <kbd>Help</kbd> > <kbd>About</kbd> button does nothing for me. Same for the <kbd>About</kbd> button in the tray. I didn't manage to open in the terminal to observe any error outputs.

Trianglify Wallpaper 2.2.0 on Kubuntu 18.04 via [snap](https://snapcraft.io/triangle-wallpaper).

**Comment by VictorioBerra** [comment]
Thanks! This is a known issue on Electron, the native about dialog is borked. I am working to replace it with my own little dialog but its low pri since its just the about dialog.

**Comment by VictorioBerra** [comment]
Fixed by https://github.com/VictorioBerra/trianglify-desktop-wallpaper/pull/7
