### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by patrycju** [VictorioBerra/trianglify-desktop-wallpaper#8]
Is it possible to add multi-monitor support in this application? I mean wallpaper is set correctly on both monitors, however, I think it would be much better looking if wallpaper on second monitor would be mirrored.

**Comment by VictorioBerra** [comment]
Unfortunately the wallpaper library im using for cross-platform wallpaper stuff only supports multi-monitor on Mac https://www.npmjs.com/package/wallpaper

If they add support for more OSes, or I find a better library I am happy to add this. I actually have code in the app already for the UI that I commented out: https://github.com/VictorioBerra/trianglify-desktop-wallpaper/blob/main/src/components/DesignerRoot.vue#L4-L22
