### ISSUE TITLE
Copying image data to the clipboard (to share a workflow with other software)

### ISSUE THREAD

**Issue by LinuxBeaver** [VictorioBerra/trianglify-desktop-wallpaper#9]
Hey, I think Trianglify would be much more suited for advance image editing task if it could copy its image data to a clipboard. That way it can be pasted in external programs (such as Gimp).

Here is an example of Trianglify, Pattern Monster and Gimp working together to make presentation captions, cards, banners ect... 

![image](https://user-images.githubusercontent.com/78667207/139507422-b5fe1888-24bd-4646-a943-3e2a4e4172e8.png)

Could you consider doing an update like this? No pressure. If you are not interested it is fine.

**Comment by VictorioBerra** [comment]
Good idea! [Done.](https://github.com/VictorioBerra/trianglify-desktop-wallpaper/commit/1bb05c3525107a76c7d2df71dc9315945dbab516)

2.3.0 - https://github.com/VictorioBerra/trianglify-desktop-wallpaper/releases/tag/v2.3.0
Snap - https://snapcraft.io/triangle-wallpaper

It should auto-update when you start it next.

![image](https://user-images.githubusercontent.com/2934507/139520768-7dc6b953-c7d7-46af-875e-03794cdbbfeb.png)

**Comment by LinuxBeaver** [comment]
Amazing. Thank you.
